### ISSUE TITLE
CustomEmailField Dashboard SSO not working

### ISSUE THREAD

**Issue by rewsmith** [TykTechnologies/tyk-identity-broker#109]
Customer TIB Dashboard SSO (oidc) not working as expected, resulting in user being logged into the Dashboard as the default `ssoSession@ssoSession.com` user.  The customer's ADFS openid provider (ADFS) does not support `/userinfo` and does not return an email claim.  In the `id_token` returned from ADFS, there is a `upn` claim which contains an email address, so assumed that setting `CustomEmailField` would result in the `upn` claim being used for email.

I have reproduced this issue using Okta IdP.  I configured Okta to return a custom claim `secondemail` and in my TIB profile I set `"CustomEmailField": "secondemail"`.  I see in the logs this custom claim is being returned by Okta, but instead of being logged in as the email address contained in the `secondemail` claim, I am logged in as `ssoSession@ssoSession.com`

[andy-TIBlog.txt](https://github.com/TykTechnologies/tyk-identity-broker/files/4911326/andy-TIBlog.txt)

[profiles-okta.json.zip](https://github.com/TykTechnologies/tyk-identity-broker/files/4911329/profiles-okta.json.zip)

**Comment by bmonteiro** [comment]
@rewsmith , I believe that info need to come from claims:

in your case you have this (missing email):

`Token claims
------------
{
  "aud": "api://default",
  "cid": "0oa4aju8l0RsefWNQ4x6",
  "exp": 1594408451,
  "iat": 1594404851,
  "iss": "https://dev-821212.okta.com/oauth2/default",
  "jti": "AT.-siX-jrlz1UEnLC9cOPPp4S2rkZgYrR962SihFdboEU",
  "scp": [
    "openid"
  ],
  "sub": "dashadmin@example.org",
  "uid": "00uazuv00GO7CRu5z4x6",
  "ver": 1
}`

and u have only `"Scopes": ["openid"],` in your profiles.json

try to pass `"Scopes": ["openid", "email"],`

then the scope email will bring in the claims ` "email": "Bla@Bla.com",`

That is the field used by TIB when it calls the SSO endpoint to get nonce and then it will appear in the dashboard.

**Comment by letzya** [comment]
So after investigation the `latest` doesn't work but when running from the source it does

```IMAGE
latest
docker pull tykio/tyk-identity-broker:latest
Last updated2 months agobytykio
DIGEST
OS/ARCH
COMPRESSED SIZE
a87d36483aa1

**Comment by letzya** [comment]
@sredxny I could not build v1.0.0-rc1 but with v0.7.1 the custom email is not working

**Comment by sredxny** [comment]
It was fixed in https://github.com/TykTechnologies/tyk-identity-broker/pull/99
Will be included in the next release.

**Comment by ilijabojanovic** [comment]
Verified on latest master
