### ISSUE TITLE
Basic Auth against LDAP integration

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk-identity-broker#11]
My use case is as follows:

a) User sends an API request w/ a basic-auth header to an exposed API on a gateway

b) I need to take that basic auth uname/pw and validate it against ldap

c) Return a 401 on authn fail, otherwise let the request proceeed

Please correct me if I am wrong, but the identity broker as I understand it, is not really a solution for this scenario? It seems to be more of just an AUTHN backend for existing token based flows, with the auth request being requested against the id broker, not just a gateway API. (per this diagram: https://tyk.io/docs/concepts/tyk-components/identity-broker/)

I need some sort of middleware hook that can do this against ldap, I don't see anything out of the box in Tyk which just supports this. (other than the IDP support for LDAP for securing the dashboard/portal only, but not just a user-defined API the gateways serve up)

**Comment by buger** [comment]
Do you consider using middleware like Python one?. Here is the example of the python plugin https://github.com/TykTechnologies/tyk-plugin-demo-python, you particularly should be interested in Auth middleware handler. 

We load the default Python runtime that’s on the system, so if you `pip install xyz` in your system the interpreter that’s loaded by Tyk will be able to import that library. So if you install `pip install python-ldap`, you will be able to run code describe here http://blog.emfeld.com/2013/03/ldap-login-authentication-using-python.html inside Authentification middleware handler.

**Comment by bitsofinfo** [comment]
Yes I've looked at those options, but before I explore them I just wanted to **_confirm that this Identity Broker add-on that everyone keeps referring me to look at is indeed NOT the solution_** for what I am talking about

**Comment by buger** [comment]
You are right in your are right that TIB will not work for your use-case, and it is more designed for oAuth like workflow.

**Comment by bitsofinfo** [comment]
Cool, thanks for the confirm!
