### ISSUE TITLE
SkipUserInfoRequest not working 

### ISSUE THREAD

**Issue by sredxny** [TykTechnologies/tyk-identity-broker#114]
**Branch/Environment**
- Branch: e.g. Master/v0.7.0
- Environment: All

**Describe the bug**
The value `SkipUserInfoRequest` is not used correctly and the request to get the user information is triggered everytime, basically we can create a profile and set this value but later the method `TAProvider.Init` is not doing anything with it, and this value should be assigned to `gProv.SkipUserInfoRequest` in the `Init` method of the social Provider.

**Reproduction steps**
1. Create a social provider for openid-connect
2. Under `ProviderConfig.UseProviders.SkipUserInfoRequest` set the value to true
3. Use the profile
4. The request to get user info is being triggered even SkipUserInfoRequest is set to true

**Actual behavior**
The request to fetch user info is being triggered everytime

**Expected behavior**
The request to fetch user info should be triggered only when `SkipUserInfoRequest` is false.

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**Browser/Os (please complete the following information):**

**Additional context**

**Comment by sredxny** [comment]
this was fixed in https://github.com/TykTechnologies/tyk-identity-broker/commit/cfaffeee0d57e5880dccfadfe8ffb00dd68a90a8

the bug lives in v0.7.0 and v0.7.1 but it was fixed in master.

**Comment by ilijabojanovic** [comment]
Verified
