### ISSUE TITLE
Panic thrown when attempting to create SSO request without sufficient configuration

### ISSUE THREAD

**Issue by jlucktay** [TykTechnologies/tyk-identity-broker#119]
**Branch/Environment**
- Branch: `master` (34d1bf51c9ca6ab70a6785bc43d7196f22642b55)
- Environment: Ara dev environment

**Describe the bug**
Panics are being thrown in the SSO process when there is some invalid Dashboard config set.

**Reproduction steps**
1. Set empty/bogus configuration under `TykApi.DashboardConfig`
2. Launch TIB
3. Hit the `/admin/sso` endpoint

**Actual behaviour**
TIB panics.

**Expected behaviour**
This section should return a clear error if creating the request returns an error:
https://github.com/TykTechnologies/tyk-identity-broker/blob/34d1bf51c9ca6ab70a6785bc43d7196f22642b55/tyk-api/tyk_api.go#L205-L209

**Screenshots/Video**

**Browser/Os (please complete the following information):**

**Additional context**
Related to an issue occurring in Ara & Tyk Dashboard.

**Comment by jlucktay** [comment]
Something like this should cover it off:
```
diff --git a/tyk-api/tyk_api.go b/tyk-api/tyk_api.go
index c78d87d..8425a96 100644
--- a/tyk-api/tyk_api.go
+++ b/tyk-api/tyk_api.go
@@ -202,10 +202,10 @@ func (t *TykAPI) DispatchDashboardSuper(target Endpoint, method string, body io.
 	preparedEndpoint := t.DashboardConfig.Endpoint + ":" + t.DashboardConfig.Port + string(target)
 
 	tykAPILogger.Debug("Calling: ", preparedEndpoint)
-	newRequest, err := http.NewRequest(method, preparedEndpoint, body)
-	if err != nil {
-		tykAPILogger.Error("Failed to create request")
-		tykAPILogger.Error(err)
+	newRequest, errNewReq := http.NewRequest(method, preparedEndpoint, body)
+	if errNewReq != nil {
+		tykAPILogger.WithError(errNewReq).Error("failed to create request")
+		return []byte{}, http.StatusInternalServerError, errNewReq
 	}
 
 	newRequest.Header.Add("admin-auth", t.DashboardConfig.AdminSecret)
```

**Comment by sredxny** [comment]
Fixed in https://github.com/TykTechnologies/tyk-identity-broker/pull/120
