### ISSUE TITLE
UseSSL doesn't respect configured port

### ISSUE THREAD

**Issue by BatmanAMA** [TykTechnologies/tyk-identity-broker#14]
Looks like main.go [L86](https://github.com/TykTechnologies/tyk-identity-broker/blob/master/main.go#L86) through 89 needs to be replicated at line 93.

**Comment by Pinpin31** [comment]
Yes I made the same modification for my need because we install Tib along the Dashboard and the Dashboard already use the port 443.
Thanks

**Comment by buger** [comment]
@BatmanAMA make sense, feel free to submit PR!
