### ISSUE TITLE
LDAP Password

### ISSUE THREAD

**Issue by alvarosIGZ** [TykTechnologies/tyk-identity-broker#17]
Hello,
So my openLDAP has password, and I don't see a field in profiles.json LDAP json configuration to add it. Is it possible to connect to a password-secured LDAP through Tyk Identity Broker?

**Comment by buger** [comment]
Can you clarify a bit about which exact password you mean? Or maybe point to OpenLDAP documentation referring such configuration.

The only thing I could find is that you provide the password to the BIND command when you need to authenticate LDAP user with his credentials — and this is definitely supported by TIB. But I could not  found info about general LDAP server password protection.

**Comment by buger** [comment]
Implemented here https://github.com/TykTechnologies/tyk-identity-broker/pull/45
