### ISSUE TITLE
[TT-2527] SAML flow cached in different profiles

### ISSUE THREAD

**Issue by bmonteiro** [TykTechnologies/tyk-identity-broker#170]
Hi @letzya , @joshblakeley 

Using version 1.1.1 because the v1.2.0 it is not working in k8s because of the #168  

The below image shows it well but still a small explanation:

- Trigger the SSO flow with TIB using the URL https://<URL>/auth/devportal/saml that will lookup the profile ID "devportal" and take it from there to SSO in the DevPortal (profile config below)

If the above is the 1st call after starting the application in k8s all other consequent calls will SSO in the DevPortal even if it is using another profile with SAML configuration.

For example: 
Trigger the SSO flow using the URL https://<URL>/auth/dash/saml should lookup the profile ID "dash" and take it from there to SSO in the Dashboard (profile config below) this is not happening because it is redirected to DevPortal again (image below)

`
..
====>>> tib-tyk-tib-tyk-pro-tib-64fcffbd77-86mzz tib-tyk-pro-tib time="May 20 10:14:31" level=debug msg="--> Looking up profile ID: dash" prefix="AUTH HANDLERS"
tib-tyk-tib-tyk-pro-tib-64fcffbd77-86mzz tib-tyk-pro-tib time="May 20 10:14:31" level=debug msg="Binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" prefix="SAML AUTH"
tib-tyk-tib-tyk-pro-tib-64fcffbd77-86mzz tib-tyk-pro-tib time="May 20 10:14:31" level=debug msg="BindingLocation: https://login.microsoftonline.com/cd203e99-2c5a-4f80-ab44-ee15c03df09c/saml2" prefix="SAML AUTH"
====>>> tib-tyk-tib-tyk-pro-tib-64fcffbd77-86mzz tib-tyk-pro-tib time="May 20 10:14:40" level=debug msg="--> Looking up profile ID: devportal" prefix="AUTH HANDLERS"
...
`

Profiles config:
`{
        "ActionType": "GenerateOrLoginUserProfile",
        "ID": "dash",
        "OrgID": "XXX",
        "CustomEmailField": "",
        "ProviderConfig": {
          "SAMLBaseURL": "https://<URL>",
          "FailureRedirect": "https://<DASH URL>/?fail=true",
          "IDPMetaDataURL": "https://login.microsoftonline.com/cd203e99-2c5a-4f80-ab44-ee15c03df09c/federationmetadata/2007-06/federationmetadata.xml?appid=14ce9a50-eb95-4bf3-bf1f-0fdb2d2490f4",
          "CertLocation":"/tmp/cert-saml.crt",
          "ForceAuthentication": true,
          "SAMLEmailClaim": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
          "SAMLForenameClaim": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname",
          "SAMLSurnameClaim": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname"
        },
        "ProviderName": "SAMLProvider",
        "Type": "redirect",
        "ReturnURL": "https://<DASH URL>/tap",
        "CustomUserGroupField": "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
        "UserGroupMapping": {
          "93b817d0-3b41-4730-a4cd-180eb56cff1b": "60a4347f5fd85e0001b0e225"
        }
      },
      {
        "ActionType": "GenerateOrLoginDeveloperProfile",
        "ID": "devportal",
        "OrgID": "XXX",
        "CustomEmailField": "",
        "IdentityHandlerConfig": {
          "DashboardCredential": "XXX"
        },
        "ProviderConfig": {
          "SAMLBaseURL": "https://<URL>",
          "FailureRedirect": "https://<DEVPORTAL URL>/login",
          "IDPMetaDataURL": "https://login.microsoftonline.com/cd203e99-2c5a-4f80-ab44-ee15c03df09c/federationmetadata/2007-06/federationmetadata.xml?appid=bc7b1fba-0d14-4045-aa00-e7cb2bd365f0",
          "CertLocation":"/tmp/cert-saml.crt",
          "ForceAuthentication": true,
          "SAMLEmailClaim": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
          "SAMLForenameClaim": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname",
          "SAMLSurnameClaim": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname"
        },
        "ProviderName": "SAMLProvider",
        "Type": "redirect",
        "ReturnURL": "https:/<DEVPORTAL URL>/sso"
      },`

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/908425/118962068-45464280-b965-11eb-8d1c-9aa8e83824b8.png">

**Comment by buger** [comment]
@sredxny ^

**Comment by bmonteiro** [comment]
Just a guess, I believe the problem is with the function` initialiseSAMLMiddleware` once it is initialised it is reused and that is not ok because it caches wrong information that will cause the problem described above.

https://github.com/TykTechnologies/tyk-identity-broker/blob/master/providers/saml.go#L87

@letzya @joshblakeley @sredxny ^^

**Comment by sredxny** [comment]
@bmonteiro Hi! so, as far as I understand the reproduction steps looks like:

1- Create 2 SAML profiles, once for dashboard SSO, another for DevPortal SSO.
2- Use the devPortal profile and get access to the portal
3- Attempt to use the dashboard SSO profile…and here, instead be redirected to dashboard we will be redirected to portal.

right?

**Comment by bmonteiro** [comment]
Correct

**Comment by bmonteiro** [comment]
@sredxny did you manage to replicate ? Can we have a unstable release to this security issue ? I can create a PR, it is probably just a simple removal so no cache, 1 line of code.

**Comment by buger** [comment]
@bmonteiro if you already have an idea of how it can be fixed if you send a PR it will defo speedup the process! 
Thanks!

**Comment by bmonteiro** [comment]
doing it now @buger if you could please create a unstable build in docker hub I would test it really quick. makes sense ?

**Comment by bmonteiro** [comment]
@buger https://github.com/TykTechnologies/tyk-identity-broker/pull/171

**Comment by buger** [comment]
@bmonteiro check v1.2.1-rc1 (both docker tag or unstable packages channel).

**Comment by bmonteiro** [comment]
@buger , it looks like master branch has other issues, so, the fix is OK and it is tested locally using ngrok with Azure AD. That said, I will push a PR to tag v1.1.1 because i used that version to test the fix and that is also the version used/deployed. The v1.2.0 was also issues.

**Comment by bmonteiro** [comment]
this one https://github.com/TykTechnologies/tyk-identity-broker/pull/173/commits

**Comment by bmonteiro** [comment]
not sure where to create it here you go https://github.com/bmonteiro/tyk-identity-broker/pull/new/v1.1.1-fix-saml-nocache

**Comment by buger** [comment]
Pls try `v1.1.2-rc1` tag.

**Comment by bmonteiro** [comment]
> Pls try `v1.1.2-rc1` tag.

  Warning  Failed     10s   kubelet            Failed to pull image "tykio/tyk-identity-broker:v1.1.2-rc1": rpc error: code = Unknown desc = Error response from daemon: manifest for tykio/tyk-identity-broker:v1.1.2-rc1 not found: manifest unknown: manifest unknown

**Comment by bmonteiro** [comment]
ok guys, for now I'm using this https://hub.docker.com/layers/bmonteiro/tyk-tib/latest/images/sha256-99f368f659585474f0099f6809d8ee4bfd6c1a533d7c91422d6c4a2fc35e616c?context=explore once it is done on your side please notify here. thx!

**Comment by buger** [comment]
@bmonteiro instead of releasing 1.1.1 we would rather to a patch for 1.2.1.
We fixed the issue which you originally mentioned, will be great if you can double check that `v1.2.1-rc4` docker image still works for you. 

Thank you!

**Comment by bmonteiro** [comment]
@sredxny can you pls share the docker image tag so I can test this fix ?

**Comment by sredxny** [comment]
@bmonteiro Hi, this is under QA process, once they confirm this is working I would be happy to share a docker image tag
