### ISSUE TITLE
LDAP provider based only on DN attribute

### ISSUE THREAD

**Issue by LordGG** [TykTechnologies/tyk-identity-broker#20]
Hello,

It seems that LDAP provider is based on DN attribute only. It is possible to select additionnal filters but the initial search depends on DN attribute.

Would it be possible to use another attribute (sAMAccountName) ? In my organization, users' DN doesn't contain login, but first name and lastname. It also contains multiple OU. 
Eg : CN=John Doe,OU=Unit1,OU=UnitB,DC=domain,DC=suffix
sAMAccountName = john.doe

I would like to be able to logon with "john.doe" as a login (instead of "John  Doe"), and authorize users from different OU.

Did I miss something or does it require an enhancement ?
Thx

**Comment by buger** [comment]
If you are using AD LDAP, it should allow bind using `samAccourntName@domainName`, and in https://tyk.io/docs/integrate/3rd-party-identity-providers/openldap/ `Using advanced LDAP search` section you can see its usage. So you specify `sAMAccountName` in both UserDN and LDAPFilter.

**Comment by LordGG** [comment]
@burger > Thank you, it works with LDAPUserDN set with the e-mail ! :)

**Comment by james-tyk** [comment]
Hi @LordGG - glad that helped. We're keen to keep improving Tyk, especially around ID Management, would you be able to answer a few questions from our team? If so, please contact me on James AT tyk.io

**Comment by LordGG** [comment]
@james-tyk , of course, I'll contact you.
