### ISSUE TITLE
Map access level groups of org to Dashboard's RBAC

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-identity-broker#32]
Related to old [#1058](https://github.com/TykTechnologies/tyk/issues/1058)

@lonelycode: The SSO needs to know which group a user belongs to first. Then map it to a Tyk Dash group. Then it can just create the nonce and forward the user.

**Comment by letzya** [comment]
What do you think - should we add the mapping to _tib.conf_ or _profiles.json_? mapping per profile or not?

**Comment by buger** [comment]
It should be mapping per profile. Should be really easy to do. Lets plan for next week. You just need to specify "GroupID" attribute in profile, and pass it to SSO API.

**Comment by letzya** [comment]
> {
>         "ActionType": "GenerateOrLoginUserProfile",
>         "ID": "ldap-dashboard",
>         "OrgID": "5a82f427e7e36f00010e4a2e",
>         "ProviderConfig": {
>                 "FailureRedirect": "http://tyk-instance.com:3000/?fail=true",
>                "LDAPBaseDN": "cn=dashboard,ou=Group,dc=ldap,dc=tyk-test,dc=com",
		"LDAPEmailAttribute": "mail",
>                 "LDAPAttributes": [],
>                 "LDAPPort": "389",
>                 "LDAPServer": "ldap.forumsys.com",
>                 "LDAPUserDN": "cn=*USERNAME*,ou=mathematicians,dc=example,dc=com"
>         },
>         "ProviderName": "ADProvider",
>        "groups" [
>                 "api -developers": [
>                       "ou=mathematicians,dc=example,dc=com",
>                       "ou=scientists,dc=example,dc=com"
>                  ]
>         ],
>         "ReturnURL": "http://tyk-instance.com:3000/tap",
>         "Type": "passthrough"
> },



So we'll have a mapping on the profile level between Tyk groups to a list of groups in the directory. Here we map a group called "api -developers" to 2 groups on the ldap server.
>        "groups" [
>                 "api -developers": [
>                       "ou=mathematicians,dc=example,dc=com",
>                       "ou=scientists,dc=example,dc=com"
>                  ]
>         ],
If the group on the ldap is wrong we'll get an ldap error during the bind or search and if the group on tyk is wrong will get an error when creating the nonce.

**Comment by buger** [comment]
@letzya nope. When you configure LDAP integration, you can make only 1 LDAP query, and if you want to fetch 2 groups of LDAP users, you need to write this expression, like this: `(|(ou=mathematicians,dc=example,dc=com),(ou=scientists,dc=example,dc=com))`. So its not job of the Tyk. We do only LDAP query -> profile mapping. 

From the technical perspective, it will just mean introducing new `GroupID` keyword located in root of profile object, where you specified BsonID of Tyk user group, which will be sent to each SSO API call.
