### ISSUE TITLE
tyk_handler responses are mixed between application/json and text/plain

### ISSUE THREAD

**Issue by dkoston** [TykTechnologies/tyk-identity-broker#4]
When trying to authenticate using a ProxyProvider for token auth for example, if you do not use a ReturnURL, a positive response will return JSON like so:

`{ "key_id": "12345" }`

However any failure response will return plaintext like so:

"Data Failure"
"Auth token generation failed"
"Login failed"

The same holds true for OAuth authentication when using NoRedirect.

This puts extra burden on login code as it must handle both JSON and plaintext responses from the same API call.

It would definitely be preferable if we could send over an 'Accept: application/json' header to get all responses back in JSON format

**Comment by lonelycode** [comment]
That's a good point, noted and on the roadmap now (or maybe a PR?) ;-)
