### ISSUE TITLE
[Question] Seem to be getting 404 no matter what from tib

### ISSUE THREAD

**Issue by Kogster** [TykTechnologies/tyk-identity-broker#6]
I'm trying to use the identity broker with the actiontype:"GenerateOAuthTokenForClient".

I have added the following profile in the profiles.json and it seems to load without issue (the number of profiles loaded when tib starts increased when I added it)

profiles.json:
```
{
    "ActionType": "GenerateOAuthTokenForClient",
    "ID": "3",
    "IdentityHandlerConfig": {
        "DashboardCredential": "{my dashboard credential}",
        "DisableOneTokenPerAPI": false,
        "OAuth": {
            "APIListenPath": "testtib",
            "BaseAPIID": "775a3ca552e241ce780c0a97b2a0b263",
            "ClientId": "7604a6f4cde541ee60f0478879a86377",
            "RedirectURI": "http://localhost:8000/final",
            "ResponseType": "token",
            "Secret": "NTFhOWFlZGEtN2Q5MC00MTA1LTc0M2MtMmUwNDI0YzcwZjcz"
        }
    },
    "MatchedPolicyID": "58b9865690f7a70001000003",
    "OrgID": "{org id}",
    "ProviderConfig": {
        "CallbackBaseURL": "http://localhost:3010",
        "FailureRedirect": "http://localhost:80/portal/login/?fail=true",
        "UseProviders": [{
            "Key": "{my google Client ID for Web application}",
            "Name": "gplus",
            "Secret": "{corresponding secret}"
        }]
    },
    "ProviderConstraints": {
        "Domain": "",
        "Group": ""
    },
    "ProviderName": "SocialProvider",
    "ReturnURL": "",
    "Type": "redirect"
}
```

TykDefinition.json oauth2 entries for the corresponding api:

```
"use_oauth2": true,
"oauth_meta": {
        "allowed_access_types": [
            "authorization_code"
        ],
        "allowed_authorize_types": [
            "token"
        ],
        "auth_login_redirect": "http://localhost:3010/"
    }

```

Now to this endpoint I am trying to post the following form bu no matter what I change the target to all I get are 404s.

```
<form role="form" method="POST" action="cc">
      <input type="hidden" class="form-control" id="response_type" name="response_type" value="token">
      <input type="hidden" class="form-control" id="client_id" name="client_id" value="aabf4d3602a64ebd67a528bd1ffbbbbf">
      <input type="hidden" class="form-control" id="redirect_uri" name="redirect_uri" value="http://localhost:8000/final">
    <button type="submit" class="btn btn-default">Start OAuth</button>
  </form>
```

I've tried and:
http://localhost:8080/testtib/oauth/authorize/
http://localhost:3010/testtib/oauth/authorize/
http://localhost:8080/testtib/oauth/authorize
http://localhost:3010/testtib/oauth/authorize

the page https://tyk.io/tyk-documentation/integrate/3rd-party-identity-providers/social-oauth/ seems to suggest that:
{listen_path}/**t**oauth/authorize

So I've tried the same as above but with toauth instead of oauth in the url.

The image on https://tyk.io/tyk-documentation/concepts/tyk-components-2/identity-broker/

Seems to show the first request going directly to tib so I tried posting everything I could think of to the port tib usesbut everything produced 404s.

What am I doing wrong?

**Comment by lonelycode** [comment]
This would be better suited in our community forum, but the URL you are sending the requests to is wrong, it must be:

```
http://tib-host:tib-port/auth/{id}/{provider}
```

So here:

```
http://tib-host:tib-port/auth/3/gplus
```

Sending a request to this URL should then trigger the whole process.

**Comment by lonelycode** [comment]
This issue has been open with no response for over a month, I'll close it for now.

**Comment by Kogster** [comment]
That's for the best. As noted by you in the first question I continued my
questions on the run forum. Which you have also answered well
