### ISSUE TITLE
Add an Identity Provider for SAML

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk-identity-broker#7]
TIB should be able to validate SAML authentication to provide access to things such as the Portal and the Dashboard

**Comment by nickReyn** [comment]
+1 from Nextiva - they really need this to be able to stop using Middleware

**Comment by asoorm** [comment]
+1 from RBS Coutts

**Comment by asoorm** [comment]
+1 from client

**Comment by egathura** [comment]
looking forward to developments on this

**Comment by chchisholm** [comment]
+1 on this guys - SAML is very basic and most companies still use it.  It seems to be a pretty big gap compared to other products like 3scale etc which all support SAML.

**Comment by buger** [comment]
> Some useful feedback from one of our users

We have an existing, in-house identity provider (IdP) that we use for SAML SSO for multiple applications. Here are some thoughts about what we would like to see from Tyk for a SAML/SSO integration:
 
·         SAML response from the IdP would include a few common attributes, like:
o   Username/user ID.
o   First and last name.
o   List of groups user is a member of.
·         Tyk would take a SAML response from our IdP and autocreate an SSO user if it does not exist, or update the user if it does. Manual user creation by an admin should not be required.
·         An administrator should be able to configure mappings between groups in an SSO response and permissions in the application. For example, if a user is in group "web dev team" in SAML response, this would automatically map their Tyk user to have "api creator" user group in Tyk Dashboard.
·         Audit detail for configuration changes in the application (e.g. creating a new API) would show the user that made the change.
·         We should be able to allow/configure fallback login with a local (non-SSO) accounts, for administrators.
·         We prefer POST based SAML (as opposed to REDIRECT).
·         SAML based logout is a nice to have but not very important.
·         SP-initiated login seems most practical here, though we do have apps with just IdP-initiated login or apps with both.

**Comment by spetrunin** [comment]
The most promising library to add SAML support:
https://github.com/crewjam/saml
- it is in the active state
- supports both redirect and post bindings
- have good documentation and samples

For testing purposes, we could use https://samltest.id/

There are not so many saml libs, most of them in abandoned state:
https://github.com/russellhaering/gosaml2 - last commit 1 year ago
https://github.com/edaniels/go-saml - fork of crewjam implementation, last commit 3 years ago
https://github.com/mattbaird/gosaml - last commit 4 years ago
https://github.com/RobotsAndPencils/go-saml - based on mattbaird implementation, last commit 3 years ago

**Comment by chchisholm** [comment]
Thank you Sergey!

**Comment by christtyk** [comment]
Definitely not stale

**Comment by bmonteiro** [comment]
I would say that saml2bearer would be good to have and the sso with the portal it is just nice to have.

@letzya
